import React from 'react';
import s from './News.module.css';

const News = () => {
    return (
        <div className={s.News}>
            News
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur accusamus optio eaque omnis voluptate repudiandae fuga laborum. Molestiae veritatis, error et exercitationem hic sed adipisci excepturi repellat, id obcaecati fugit?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis in eveniet sapiente laboriosam doloribus inventore esse eligendi repellendus quas deserunt eum accusantium asperiores id praesentium magnam illo, odit vitae officia minima perspiciatis! Numquam recusandae autem porro, mollitia tenetur distinctio? Quisquam nemo adipisci quasi sequi tenetur, eum placeat. Officiis unde adipisci earum suscipit, error doloribus recusandae atque quam quisquam praesentium facilis repudiandae deleniti nulla quidem voluptatibus delectus veniam consequatur rerum ipsa. Temporibus, atque, eligendi excepturi nemo, voluptatem asperiores animi autem laborum iste possimus fugit ipsum qui similique quas repudiandae nisi dolores blanditiis. Ratione molestiae voluptatum a quidem vitae eos nesciunt.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur accusamus optio eaque omnis voluptate repudiandae fuga laborum. Molestiae veritatis, error et exercitationem hic sed adipisci excepturi repellat, id obcaecati fugit?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis in eveniet sapiente laboriosam doloribus inventore esse eligendi repellendus quas deserunt eum accusantium asperiores id praesentium magnam illo, odit vitae officia minima perspiciatis! Numquam recusandae autem porro, mollitia tenetur distinctio? Quisquam nemo adipisci quasi sequi tenetur, eum placeat. Officiis unde adipisci earum suscipit, error doloribus recusandae atque quam quisquam praesentium facilis repudiandae deleniti nulla quidem voluptatibus delectus veniam consequatur rerum ipsa. Temporibus, atque, eligendi excepturi nemo, voluptatem asperiores animi autem laborum iste possimus fugit ipsum qui similique quas repudiandae nisi dolores blanditiis. Ratione molestiae voluptatum a quidem vitae eos nesciunt.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur accusamus optio eaque omnis voluptate repudiandae fuga laborum. Molestiae veritatis, error et exercitationem hic sed adipisci excepturi repellat, id obcaecati fugit?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis in eveniet sapiente laboriosam doloribus inventore esse eligendi repellendus quas deserunt eum accusantium asperiores id praesentium magnam illo, odit vitae officia minima perspiciatis! Numquam recusandae autem porro, mollitia tenetur distinctio? Quisquam nemo adipisci quasi sequi tenetur, eum placeat. Officiis unde adipisci earum suscipit, error doloribus recusandae atque quam quisquam praesentium facilis repudiandae deleniti nulla quidem voluptatibus delectus veniam consequatur rerum ipsa. Temporibus, atque, eligendi excepturi nemo, voluptatem asperiores animi autem laborum iste possimus fugit ipsum qui similique quas repudiandae nisi dolores blanditiis. Ratione molestiae voluptatum a quidem vitae eos nesciunt.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur accusamus optio eaque omnis voluptate repudiandae fuga laborum. Molestiae veritatis, error et exercitationem hic sed adipisci excepturi repellat, id obcaecati fugit?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis in eveniet sapiente laboriosam doloribus inventore esse eligendi repellendus quas deserunt eum accusantium asperiores id praesentium magnam illo, odit vitae officia minima perspiciatis! Numquam recusandae autem porro, mollitia tenetur distinctio? Quisquam nemo adipisci quasi sequi tenetur, eum placeat. Officiis unde adipisci earum suscipit, error doloribus recusandae atque quam quisquam praesentium facilis repudiandae deleniti nulla quidem voluptatibus delectus veniam consequatur rerum ipsa. Temporibus, atque, eligendi excepturi nemo, voluptatem asperiores animi autem laborum iste possimus fugit ipsum qui similique quas repudiandae nisi dolores blanditiis. Ratione molestiae voluptatum a quidem vitae eos nesciunt.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur accusamus optio eaque omnis voluptate repudiandae fuga laborum. Molestiae veritatis, error et exercitationem hic sed adipisci excepturi repellat, id obcaecati fugit?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis in eveniet sapiente laboriosam doloribus inventore esse eligendi repellendus quas deserunt eum accusantium asperiores id praesentium magnam illo, odit vitae officia minima perspiciatis! Numquam recusandae autem porro, mollitia tenetur distinctio? Quisquam nemo adipisci quasi sequi tenetur, eum placeat. Officiis unde adipisci earum suscipit, error doloribus recusandae atque quam quisquam praesentium facilis repudiandae deleniti nulla quidem voluptatibus delectus veniam consequatur rerum ipsa. Temporibus, atque, eligendi excepturi nemo, voluptatem asperiores animi autem laborum iste possimus fugit ipsum qui similique quas repudiandae nisi dolores blanditiis. Ratione molestiae voluptatum a quidem vitae eos nesciunt.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur accusamus optio eaque omnis voluptate repudiandae fuga laborum. Molestiae veritatis, error et exercitationem hic sed adipisci excepturi repellat, id obcaecati fugit?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis in eveniet sapiente laboriosam doloribus inventore esse eligendi repellendus quas deserunt eum accusantium asperiores id praesentium magnam illo, odit vitae officia minima perspiciatis! Numquam recusandae autem porro, mollitia tenetur distinctio? Quisquam nemo adipisci quasi sequi tenetur, eum placeat. Officiis unde adipisci earum suscipit, error doloribus recusandae atque quam quisquam praesentium facilis repudiandae deleniti nulla quidem voluptatibus delectus veniam consequatur rerum ipsa. Temporibus, atque, eligendi excepturi nemo, voluptatem asperiores animi autem laborum iste possimus fugit ipsum qui similique quas repudiandae nisi dolores blanditiis. Ratione molestiae voluptatum a quidem vitae eos nesciunt.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur accusamus optio eaque omnis voluptate repudiandae fuga laborum. Molestiae veritatis, error et exercitationem hic sed adipisci excepturi repellat, id obcaecati fugit?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis in eveniet sapiente laboriosam doloribus inventore esse eligendi repellendus quas deserunt eum accusantium asperiores id praesentium magnam illo, odit vitae officia minima perspiciatis! Numquam recusandae autem porro, mollitia tenetur distinctio? Quisquam nemo adipisci quasi sequi tenetur, eum placeat. Officiis unde adipisci earum suscipit, error doloribus recusandae atque quam quisquam praesentium facilis repudiandae deleniti nulla quidem voluptatibus delectus veniam consequatur rerum ipsa. Temporibus, atque, eligendi excepturi nemo, voluptatem asperiores animi autem laborum iste possimus fugit ipsum qui similique quas repudiandae nisi dolores blanditiis. Ratione molestiae voluptatum a quidem vitae eos nesciunt.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur accusamus optio eaque omnis voluptate repudiandae fuga laborum. Molestiae veritatis, error et exercitationem hic sed adipisci excepturi repellat, id obcaecati fugit?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis in eveniet sapiente laboriosam doloribus inventore esse eligendi repellendus quas deserunt eum accusantium asperiores id praesentium magnam illo, odit vitae officia minima perspiciatis! Numquam recusandae autem porro, mollitia tenetur distinctio? Quisquam nemo adipisci quasi sequi tenetur, eum placeat. Officiis unde adipisci earum suscipit, error doloribus recusandae atque quam quisquam praesentium facilis repudiandae deleniti nulla quidem voluptatibus delectus veniam consequatur rerum ipsa. Temporibus, atque, eligendi excepturi nemo, voluptatem asperiores animi autem laborum iste possimus fugit ipsum qui similique quas repudiandae nisi dolores blanditiis. Ratione molestiae voluptatum a quidem vitae eos nesciunt.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur accusamus optio eaque omnis voluptate repudiandae fuga laborum. Molestiae veritatis, error et exercitationem hic sed adipisci excepturi repellat, id obcaecati fugit?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis in eveniet sapiente laboriosam doloribus inventore esse eligendi repellendus quas deserunt eum accusantium asperiores id praesentium magnam illo, odit vitae officia minima perspiciatis! Numquam recusandae autem porro, mollitia tenetur distinctio? Quisquam nemo adipisci quasi sequi tenetur, eum placeat. Officiis unde adipisci earum suscipit, error doloribus recusandae atque quam quisquam praesentium facilis repudiandae deleniti nulla quidem voluptatibus delectus veniam consequatur rerum ipsa. Temporibus, atque, eligendi excepturi nemo, voluptatem asperiores animi autem laborum iste possimus fugit ipsum qui similique quas repudiandae nisi dolores blanditiis. Ratione molestiae voluptatum a quidem vitae eos nesciunt.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur accusamus optio eaque omnis voluptate repudiandae fuga laborum. Molestiae veritatis, error et exercitationem hic sed adipisci excepturi repellat, id obcaecati fugit?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis in eveniet sapiente laboriosam doloribus inventore esse eligendi repellendus quas deserunt eum accusantium asperiores id praesentium magnam illo, odit vitae officia minima perspiciatis! Numquam recusandae autem porro, mollitia tenetur distinctio? Quisquam nemo adipisci quasi sequi tenetur, eum placeat. Officiis unde adipisci earum suscipit, error doloribus recusandae atque quam quisquam praesentium facilis repudiandae deleniti nulla quidem voluptatibus delectus veniam consequatur rerum ipsa. Temporibus, atque, eligendi excepturi nemo, voluptatem asperiores animi autem laborum iste possimus fugit ipsum qui similique quas repudiandae nisi dolores blanditiis. Ratione molestiae voluptatum a quidem vitae eos nesciunt.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur accusamus optio eaque omnis voluptate repudiandae fuga laborum. Molestiae veritatis, error et exercitationem hic sed adipisci excepturi repellat, id obcaecati fugit?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis in eveniet sapiente laboriosam doloribus inventore esse eligendi repellendus quas deserunt eum accusantium asperiores id praesentium magnam illo, odit vitae officia minima perspiciatis! Numquam recusandae autem porro, mollitia tenetur distinctio? Quisquam nemo adipisci quasi sequi tenetur, eum placeat. Officiis unde adipisci earum suscipit, error doloribus recusandae atque quam quisquam praesentium facilis repudiandae deleniti nulla quidem voluptatibus delectus veniam consequatur rerum ipsa. Temporibus, atque, eligendi excepturi nemo, voluptatem asperiores animi autem laborum iste possimus fugit ipsum qui similique quas repudiandae nisi dolores blanditiis. Ratione molestiae voluptatum a quidem vitae eos nesciunt.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur accusamus optio eaque omnis voluptate repudiandae fuga laborum. Molestiae veritatis, error et exercitationem hic sed adipisci excepturi repellat, id obcaecati fugit?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis in eveniet sapiente laboriosam doloribus inventore esse eligendi repellendus quas deserunt eum accusantium asperiores id praesentium magnam illo, odit vitae officia minima perspiciatis! Numquam recusandae autem porro, mollitia tenetur distinctio? Quisquam nemo adipisci quasi sequi tenetur, eum placeat. Officiis unde adipisci earum suscipit, error doloribus recusandae atque quam quisquam praesentium facilis repudiandae deleniti nulla quidem voluptatibus delectus veniam consequatur rerum ipsa. Temporibus, atque, eligendi excepturi nemo, voluptatem asperiores animi autem laborum iste possimus fugit ipsum qui similique quas repudiandae nisi dolores blanditiis. Ratione molestiae voluptatum a quidem vitae eos nesciunt.
            
        </div>
    );
};

export default News;